### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xbal023** [azize-corbinnn/My-Portfolio-wv#1]
Gak ada bug si, mas Fajar emang Jago

**Comment by azize-corbinnn** [comment]
oyy jangann bang jangan diliatt ini maa pemulaa bangett

Pada tanggal Min, 27 Agu 2023 15.47, bolaxd ***@***.***>
menulis:

**Comment by xbal023** [comment]
Jar, minta WA kmu, nomor ku ganti jar, kebanned

**Comment by azize-corbinnn** [comment]
083862591504 kebanned pasti acak acak wa ka  akwkwkw

Pada tanggal Min, 27 Agu 2023 16.09, bolaxd ***@***.***>
menulis:

**Comment by xbal023** [comment]
Wkwkwk, isengin nantang orang buat adu bug malah di banned :v
